
development:
  adapter: postgresql
  encoding: utf8
  database: bibapp_development
  username: root
  password: maheshwari
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: bibapp_test
  username: root
  password: maheshwari
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: bibapp_test
  username: root
  password: maheshwari
  host: localhost

